### ISSUE TITLE
Support multiple config per field via `alias`/`name`

### ISSUE THREAD

**Issue by PowerKiKi** [Ecodev/natural-search#16]
# Mixed up selections

Today natural-search let us configure the same field more than once, such as:

```ts
const config1: NaturalSearchConfiguration = [
    {
        field: 'date',
        display: 'Real date',
        component: TypeDateRangeComponent,  // This is the important difference, not shown in screenshot below but actually exist
    },
    {
        field: 'date',
        display: 'Textual date',
    },
];
```

Then if we attempt to set a selection for the textual version of the date, we would do it like so:

```ts
const selections: NaturalSearchSelections = [
    [
        {
            field: 'date',
            condition: {
                like: {value: 'foo'},
            },
        },
    ],
];
```

And because the selection has no way to specify if it is targeting the actual or textual date, then natural-search would incorrectly assume it is the an actual date. But the textual condition is obviously invalid for an actual date, so it will be incorrectly shown as an invalid actual date:

![image](https://user-images.githubusercontent.com/72603/43623151-ac39e48a-971a-11e8-9593-760902832a88.png)

# Mixed up transforms

Similar for `transform` functions. If configuration and selection is the following:

```ts
const config1: NaturalSearchConfiguration = [
    {
        field: 'date',
        display: 'Version A',
        transform: (s: Selection) => {
            if (s.condition.like) {
                s.condition.like.value = 'Version A';
            }
            return s;
        },
    },
    {
        field: 'date',
        display: 'Version B',
        transform: (s: Selection) => {
            if (s.condition.like) {
                s.condition.like.value = 'Version B';
            }
            return s;
        },
    },
];

const selections: NaturalSearchSelections = [
    [
        {
            field: 'date',
            condition: {
                like: {value: 'foo'},
            },
        },
    ],
];
```

Then we would have no way to correctly apply transform for Version B and we would always get a GraphQL selection like:

```json
{
  "groups": [
    {
      "conditions": [
        {
          "date": {
            "like": {
              "value": "Version A"
            }
          }
        }
      ]
    }
  ]
}
```

# Cause

The cause of this is the `getConfigurationFromSelection` function who is used for both cases and use only the field name to match a configuration and a selection. So of course if there are multiple identical field names, it cannot know which one we really need.

# Possible solution

Enforce the uniqueness of field names by changing the configuration structure to have the field name as key for the `ItemConfiguration` like so:

```ts
/**
 * The key `field` is the field the item configuration should apply to.
 *
 * In most cases it should be the property name of the model. Something like:
 *
 * - name
 * - description
 * - artist.name
 */
export type NaturalSearchConfigurationVersion2 = { [field: string]: ItemConfiguration };


// No `field` anymore
export interface BasicConfigurationVersion2 {
    display: string;
    transform?: (Selection) => Selection;
}
```

And similar for selection:

```ts
export type GroupSelections = { [field: string]: FilterGroupConditionField };

// Probably entirely deleted
// export interface Selection {
//     field: string;
//     condition: FilterGroupConditionField;
// }
```

# Alternatives ?

Could we find a way to somehow modify `getConfigurationFromSelection`, or remove its use entirely, to be able to link a selection with its configuration ?

**Comment by PowerKiKi** [comment]
A possible alternative would be to add a new field, something like `alias` or `key`, next to `field`. `field` stays as always required, but `alias` is optional and can be used when we need to use more than one time the same `field`.

So something like that:

```ts
const config1: NaturalSearchConfiguration = [
    {
        field: 'date',
        alias: 'realDate',
        display: 'Real date',
        component: TypeDateRangeComponent,  // This is the important difference, no shown in screenshot below but actually exist
    },
    {
        field: 'date',
        alias: 'textualDate',
        display: 'Textual date',
    },
];
```

If `alias` exists it will be used by `getConfigurationFromSelection` instead of `field` to match a selection with its configuration. So a selection must be given with the `alias`, instead of the `field`. And it will also be present in the URL. But it will never appear in the GraphQL selection.

A new method should be added to validate that any given configuration has unique aliases/fields, or throw an error if it doesn't.

This makes the configuration a little bit more complicated but would be a non breaking change and keep a lot of flexibility. As a side-effect, it could also be a way to shorten URL by using short (non-readable) aliases.

**Comment by sambaptista** [comment]
I would prefer the second last option using `alias` attribute, that I would name `name` for `configurationName`. 

Setting it optional and using `field` as fallback cause the change to be non-breaking.

I prefer this solution because we don't have to change deeply our current code.

**Comment by PowerKiKi** [comment]
`name` sounds good. So this become non-breaking.

**Comment by sambaptista** [comment]
Implemented
