### ISSUE TITLE
Inputs (configuration du composant) et interfaces correspondantes

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural-search#2]
## Recherche texte global

![recherche 1 1](https://user-images.githubusercontent.com/5111137/39055803-700387d0-44b5-11e8-9d98-7f949f7d5dc4.png)

## Recherche texte sur un attribut
![recherche 2](https://user-images.githubusercontent.com/5111137/39055873-94daf584-44b5-11e8-92b3-9b148a52f52f.png)

La recherche texte est celle par défaut pour une config qui n'a pas de spécification :

```
[
  {
     display: 'Artiste',
     attribute: 'artiste',
  }
]
```

Une fois validé, un nouveau bloc apparaît.
![recherche 3](https://user-images.githubusercontent.com/5111137/39055901-9fbd956a-44b5-11e8-88a9-1938403eb28b.png)

## Recherche dans une liste
![recherche 3 1](https://user-images.githubusercontent.com/5111137/39056671-a7c365bc-44b7-11e8-8118-6c41790fdb15.png)

Valeurs prédéfinies en tant que tableau de strings :

```
[
  {
     display: 'Artiste',
     attribute: 'artiste',
     values: ['Picasso', 'Van Gogh'],
  }
]
```
Valeurs prédéfinies en tant que tableau d'objets
```
[
  {
     display: 'Artiste',
     attribute: 'artiste',
     values: [{id: 1, name : 'Picasso'}, {id: 2, fullName : 'Van Gogh'}],
     valuesDisplayFn = (item) => item.fullName ? item.fullName : item.name,
  }
]
```

Valeurs prédéfinie, post-loadées :
```
[
  {
     display: 'Artiste',
     attribute: 'artiste',
     values: artistsDataSource,
     valuesDisplayFn = (item) => item.fullName ? item.fullName : item.name,
  }
]
```
Une DataSource reprend les principes de CDK / Material2. Elle dispose d'une fonction .connect() qui permet à natural-search de compléter les valeurs à afficher quand elles sont disponibles.

Valeurs prédéfinie auto-complétées :
```
[
  {
     display: 'Artiste',
     attribute: 'artiste',
     autocompleteValues: artistsAutocompleteDataSource,
     valuesDisplayFn = (item) => item.fullName ? item.fullName : item.name,
  }
]
```
Une AutocompleteDataSource étend une DataSource mais reçoit en plus un observable qui représente les variables de la query. Ainsi elle est autonome pour faire correspondre la recherche de l'utilisateur dans le natural-search et recevoir les résultats correspondant.

## Recherche dans un champ numérique
![recherche 3 2](https://user-images.githubusercontent.com/5111137/39057663-1389e238-44ba-11e8-9fa7-ff84feda2d6a.png)

Numéro simple :
```
[
  {
     display: 'Taille',
     attribute: 'size',
     type: 'numeric',
     min : 0,
     max : 100
  }
]
```
Plage :
```
[
  {
     display: 'Taille',
     attribute: 'size',
     type: 'range',
     min : 0,
     max : 100,
     minRequired : false,
     maxRequired: true,
  }
]
```
Tel que configuré ci-dessus, la plage autorise un maximum, mais pas un minimum ce qui signifie un numéro plus petit que 100 doit être entré pour valider le filtre.

Valeurs discrètes :
```
[
  {
     display: 'Taille',
     attribute: 'size',
     type: 'range', // si indéfini, n'acceptera qu'une valeur
     values : [0, 3, 7, 11, 13, 17],
     minRequired : false,
     maxRequired: true,
  }
]
```
Dans ce cas, si l'utilisateur saisie un numéro entre les valeurs fournies, il sera remplacé par le plus proche.

## Mais encore ...
D'autres types pourront venir enrichir cette liste non exhaustive, p.ex un slider pourrait être l'une des prochaines étapes pour les valeurs numériques. Le slider d'okpilot, bien que trop complet a été conçu dans la lignée des composants et pourrait assez facilement être porté ici.

**Comment by PowerKiKi** [comment]
J'avais déjà noté les besoins pour les types suivant:

| type| prévu |
|--|--|
| un choix parmi une liste | manque option pour choisir un ou plusieurs dans une liste|
| plusieurs choix parmi un arbre (sélection groupe) | :x: |
| case à cocher | :x: |
| textuelle |:heavy_check_mark: |
| plage de dates | :x: |
| case à cocher spéciale "montrer éléments de toutes les check-lists actives" | :x: |

Parmi les manquants, l'arbre me semble particulièrement important. Et il est essentiel que nous puissions intégrer d'une façon ou d'une autre notre sélecteur hiérarchique. Un type custom avec moyen de lui donner un composant custom me vient à l'esprit.

Et du coup je me demande si on pourrait pas avoir un système de "plugins" de types. Nous implémenterions qq types de bases, sous la forme de plugin, et l'utilisateur pourrait ajouter (ou supprimer ?) des types en fonction de ses besoins.

Si on réfléchit comme cela, il faudrait définir ce qu'est un type. A mon avis c'est:

- un nom (qui est utilisé pour configurer le natural-search)
- un composant, qui est utilisé en popup pour sélectionner une/des valeurs
- une configuration qui est propre à son composant (à priori les valeurs possible, l'autocomplete, etc.)
- une fonction pour rendre les valeurs actuellement sélectionnée

Le nom pourrait simplement être le nom de la classe du composant. On pourrait définir des interfaces qui ressemble à:

```ts
export interface TypeInterface {
    /**
     * Set the custom configuration for the type
     * such as data source for possible values, display
     * function for a value, etc.
     */
    setConfiguration(configuration: any): void;

    /**
     * Return a string representing all currently selected values
     */
    renderCurrentlySelectedValues(): string;
}

export interface TypeNumericConfiguration {
    min?: number,
    max?: number,
}

export interface TypeRangeConfiguration implements TypeNumericConfiguration {
    minRequired: boolean,
    maxRequired: boolean,
}

@Component({
    /* component stuff ... */
})
export class TypeNumericComponent implements TypeInterface {

    setConfiguration(configuration: TypeNumericConfiguration): void {
    }

    renderCurrentlySelectedValues(): string {
        return undefined;
    }
}

export interface SearchConfiguration {
    [index: number]: {
        display: string,
        attribute: string,
        component: any,
        configuration: any,
    }
}
```

Et l'utilisation pourrait vaguement être qqch comme:
```ts
@Component({
    selector: 'app-some-page',
    template: `
        <div>
            <p>Some awesome search bar:</p>
            <natural-search [configuration]="searchConfiguration"></natural-search>
        </div>`,
})
export class SomePageComponent {
    public searchConfiguration: SearchConfiguration = [
        {
            display: 'Artiste',
            attribute: 'artist',
            component: TypeNumericComponent,
            configuration: {
                min: 0,
                max: 100,
            },
        },
    ];
}
```

Ces interfaces sont absolument pas définitives. On pourrait trouver des noms un peu mieux, mais surtout je suis pas convaincu de la simplicité de `attribute`. A mon avis c'est plus compliqué que cela. Mais je penses qu'on peut en parler dans #1.

**Comment by PowerKiKi** [comment]
more or less implemented
